### ISSUE TITLE
Example ipynb to render on github - ggplot not working?

### ISSUE THREAD

**Issue by vnijs** [IRkernel/IRkernel#126] opened 2015-05-07 20:00 UTC
With the announcement that ipynb's can be rendered on GitHub I was looking for some examples. The demo.ipynb is useful. Thanks.

I try to create another example notebook but ran into a problem with ggplot2. The following produces:

library(ggplot2)
ggplot(mtcars, aes(x = mpg, y = cyl)) + geom_point()

plot without title

Any additional examples you can post would be great

**Comment by JanSchulz** [comment] 2015-05-07 21:42
Could be this: https://github.com/IRkernel/IRkernel/issues/125

**Comment by takluyver** [comment] 2015-05-08 23:13
I think that sounds like a different error. @vnijs , can you show the output of `capabilities()`?

**Comment by takluyver** [comment] 2015-05-08 23:14
Actually, looking through the issues, it sounds like a duplicate of #122. Are you on OS X?

**Comment by vnijs** [comment] 2015-05-08 23:35
Yes I am. Base graphics are rendered. FYI base graphics are not shown when an ipynb is rendered on Github (https://github.com/IRkernel/IRkernel/blob/master/Demo.ipynb)

**Comment by takluyver** [comment] 2015-05-09 00:27
Thanks for letting us know - I've filed jupyter/nbviewer#453 about the Github issue.

Closing this as probably the same as #122.

**Closed by takluyver** 2015-05-09 00:27 UTC
Labels: plotting
