### ISSUE TITLE
Getting Error: Command Failed(1)

### ISSUE THREAD

**Issue by hafizurcse** [IRkernel/IRkernel#393] opened 2016-08-12 09:31 UTC
This `install.packages(c('repr', 'IRdisplay', 'crayon', 'pbdZMQ', 'devtools'))` works fine but I am getting error in `devtools::install` as follows (look at the last line)

```r
> devtools::install_github('IRkernel/IRkernel') # My command
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
Downloading GitHub repo IRKernel/IRdisplay@master
from URL https://api.github.com/repos/IRKernel/IRdisplay/zipball/master
Installing IRdisplay
"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hafiz/AppData/Local/Temp/Rtmp2vcmaP/devtools1f5429781512/IRkernel-IRdisplay-6f27575"  \
  --library="C:/Users/Hafiz/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'IRdisplay' ...
** R
** tests
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (IRdisplay)
"C:/PROGRA~1/R/R-33~1.1/bin/i386/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/Hafiz/AppData/Local/Temp/Rtmp2vcmaP/devtools1f544f9e3b84/IRkernel-IRkernel-66e4fdd"  \
  --library="C:/Users/Hafiz/Documents/R/win-library/3.3" --install-tests 

* installing *source* package 'IRkernel' ...
** R
** inst
** tests
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringr'
ERROR: lazy loading failed for package 'IRkernel'
* removing 'C:/Users/Hafiz/Documents/R/win-library/3.3/IRkernel'
Error: Command failed (1)
```

**Comment by flying-sheep** [comment] 2016-08-12 09:40
please look at the 4th to last line, which should be an error you can fix :wink:

**Comment by hafizurcse** [comment] 2016-08-12 11:06
i m very poor in setting up things. when i write the command it does n't ask me to give the location and i get an error. i m not sure what path i have to provide. 

Just few details so that you can answer it in way which i understand.
R library location: C:\Users\Hafiz\Documents\R\win-library\3.3
My Location of R setup: C:\Program Files\R\R-3.3.1\bin
Location where package is already downloaded: C:\Users\Hafiz\AppData\Local\Temp\Rtmp2vcmaP\devtools1f5429781512
Can you please guide how and where to fix?

**Comment by takluyver** [comment] 2016-08-12 11:09
I think this is the line @flying-sheep meant:

```
there is no package called 'stringr'
```

Hopefully it should be just a matter of installing `stringr` and then trying to install IRkernel again.

**Comment by hafizurcse** [comment] 2016-08-12 11:21
@takluyver  Thank you so much. It is now installed.

**Comment by takluyver** [comment] 2016-08-12 11:39
Great, you're welcome.

@flying-sheep I take it the fix for this is just getting the release on CRAN? If so, feel free to close this issue.

**Comment by flying-sheep** [comment] 2016-08-12 12:42
i have no idea. we don’t call into stringr, so something somewhere has a undeclared dependency on it. not our bug in any case

**Comment by takluyver** [comment] 2016-08-12 12:53
How might we figure out where the bug is and try to get it fixed? Just saying 'not our bug' doesn't seem terribly constructive. Maybe the authors of whichever piece the bug is in haven't noticed it for some reason.

There's also a selfish motivation for getting it fixed: it reduces the number of questions we have to field about it in the future.

**Comment by flying-sheep** [comment] 2016-08-12 12:55
i didn’t mean it in the way that i don’t care about it, i meant it in the way that it shouldn’t (and likely can’t) be fixed in this repo

**Comment by takluyver** [comment] 2016-08-12 12:58
Good, that's what I hoped. :-)

Do you have any idea how we can work out which package is missing a dependency?

**Comment by flying-sheep** [comment] 2016-08-12 16:39
hard if this isn’t reproducible. it seems to appear during installation of `IRdisplay`. maybe we can use `install.packages` with `lib` set to a new location (or in a chroot) to reproduce this, and if we can reproduce it, we can inspect what part of lazy-loading IRdisplay recursively invokes stringr

**Comment by flying-sheep** [comment] 2016-08-14 08:31
since #395 was opened and is more specific, i’m closing this

**Closed by flying-sheep** 2016-08-14 08:32 UTC
Labels: tech support

**Comment by vedatAltun** [comment] 2018-03-17 11:24
#Error: Command failed (1) 
 for Ubuntu 16.04 you can try this 
sudo apt-get install libxml2-dev or sudo apt-get install libxml2
