### ISSUE TITLE
Problem in unicode in R from jupyternotebook

### ISSUE THREAD

**Issue by githubPratima** [IRkernel/IRkernel#731] opened 2023-02-03 16:56 UTC
Someone, please help to solve this problem.. when I run some code in R kernel in jupyternotebook I am getting this error..

> Your code contains a unicode char which cannot be displayed in your
> current locale and R will silently convert it to an escaped form when the
> R kernel executes this code. This can lead to subtle errors if you use
> such chars to do comparisons. For more information, please see
> https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows
> ```
> Error in parse(text = x, srcfile = src): <text>:12:1: unexpected '<'
> 11: }
> 12: <
>     ^
> Traceback:
> ```

**Comment by flying-sheep** [comment] 2023-02-03 19:48
I accidentally deactivated the wiki page the link goes to. It’s restored now, please read: https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows

In https://github.com/r-lib/evaluate/issues/66, I commented that unicode is supported since R 4.2.

So please upgrade to R 4.2 and check if the problem is gone. I’m going to close this issue assuming it is solved with R 4.2. If not, please comment in this issue to let me know and I’ll reopen it and investigate. In that case, please also add a screenshot, and specify your R version.

**Closed by flying-sheep** 2023-02-03 19:48 UTC
