### ISSUE TITLE
Calling nycflights13 dataframe hangs kernel

### ISSUE THREAD

**Issue by rsmith31415** [IRkernel/IRkernel#174] opened 2015-08-03 14:25 UTC
Running a particular dataframe (from the nycflights13 package) makes the kernel to hang:

```
library(nycflights13)
data(flights)
flights
```

I noticed the last call is not returning a get_shell_msg() and get_iopub_msg() doesn't seem to be finish. This is the output I get using the kernel directly:

```
In [9]: kc.execute('library(nycflights13); data(flights); ls()')
Out[9]: '49ff5db7-9400-4ddc-a559-1ae37050c763'

In [10]: kc.get_shell_msg(timeout=1)
Out[10]:
{'buffers': [],
 'content': {u'execution_count': 1,
  u'payload': [],
  u'status': u'ok',
  u'user_expressions': {}},
 'header': {u'msg_id': u'9f43398b-0f34-4307-a985-d97c4a8d5916',
  u'msg_type': u'execute_reply',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'9f43398b-0f34-4307-a985-d97c4a8d5916',
 'msg_type': u'execute_reply',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 49, 30, 890131),
  u'msg_id': u'49ff5db7-9400-4ddc-a559-1ae37050c763',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [11]: kc.get_iopub_msg(timeout=1)
Out[11]:
{'buffers': [],
 'content': {u'execution_state': u'busy'},
 'header': {u'msg_id': u'7023fb15-c445-44f7-9251-452b16b9d9d4',
  u'msg_type': u'status',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'7023fb15-c445-44f7-9251-452b16b9d9d4',
 'msg_type': u'status',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 49, 30, 890131),
  u'msg_id': u'49ff5db7-9400-4ddc-a559-1ae37050c763',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [12]: kc.get_iopub_msg(timeout=1)
Out[12]:
{'buffers': [],
 'content': {u'code': u'library(nycflights13); data(flights); ls()',
  u'execution_count': 1},
 'header': {u'msg_id': u'5d982d5c-823f-4901-8147-62be8e5b5f45',
  u'msg_type': u'execute_input',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'5d982d5c-823f-4901-8147-62be8e5b5f45',
 'msg_type': u'execute_input',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 49, 30, 890131),
  u'msg_id': u'49ff5db7-9400-4ddc-a559-1ae37050c763',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [13]: kc.get_iopub_msg(timeout=1)
Out[13]:
{'buffers': [],
 'content': {u'data': {u'text/html': u"'flights'",
   u'text/latex': u"'flights'",
   u'text/markdown': u"'flights'",
   u'text/plain': u'[1] "flights"'},
  u'execution_count': 1,
  u'metadata': {}},
 'header': {u'msg_id': u'd316615b-41aa-4f27-987a-25cdd8d26d5a',
  u'msg_type': u'execute_result',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'd316615b-41aa-4f27-987a-25cdd8d26d5a',
 'msg_type': u'execute_result',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 49, 30, 890131),
  u'msg_id': u'49ff5db7-9400-4ddc-a559-1ae37050c763',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [14]: kc.get_iopub_msg(timeout=1)
Out[14]:
{'buffers': [],
 'content': {u'execution_state': u'idle'},
 'header': {u'msg_id': u'09c6548e-461c-46fe-aa88-fc78b207505e',
  u'msg_type': u'status',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'09c6548e-461c-46fe-aa88-fc78b207505e',
 'msg_type': u'status',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 49, 30, 890131),
  u'msg_id': u'49ff5db7-9400-4ddc-a559-1ae37050c763',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [15]: kc.execute('flights')
Out[15]: 'ddaf08b9-02e3-47a6-8e08-45bd519f79b8'

In [16]: kc.get_shell_msg(timeout=1)
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
<ipython-input-16-0a8619c215d5> in <module>()
----> 1 kc.get_shell_msg(timeout=1)

/home/user/anaconda/lib/python2.7/site-packages/IPython/kernel/client.pyc in get_shell_msg(self, *args, **kwargs)
     78     def get_shell_msg(self, *args, **kwargs):
     79         ""Get a message from the shell channel""
---> 80         return self.shell_channel.get_msg(*args, **kwargs)
     81
     82     def get_iopub_msg(self, *args, **kwargs):

/home/user/anaconda/lib/python2.7/site-packages/IPython/kernel/blocking/channels.pyc in get_msg(self, block, timeout)
     55             return self._recv()
     56         else:
---> 57             raise Empty
     58
     59     def get_msgs(self):

Empty:

In [17]: kc.get_iopub_msg(timeout=5)
Out[17]:
{'buffers': [],
 'content': {u'execution_state': u'busy'},
 'header': {u'msg_id': u'34b2fcc4-5244-42d6-9ac8-2b287cbf9a76',
  u'msg_type': u'status',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'34b2fcc4-5244-42d6-9ac8-2b287cbf9a76',
 'msg_type': u'status',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 50, 10, 152110),
  u'msg_id': u'ddaf08b9-02e3-47a6-8e08-45bd519f79b8',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [18]: kc.get_iopub_msg(timeout=5)
Out[18]:
{'buffers': [],
 'content': {u'code': u'flights', u'execution_count': 2},
 'header': {u'msg_id': u'ee48022a-4650-4630-a062-cb5dbdc3370d',
  u'msg_type': u'execute_input',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'},
 'metadata': {},
 'msg_id': u'ee48022a-4650-4630-a062-cb5dbdc3370d',
 'msg_type': u'execute_input',
 'parent_header': {u'date': datetime.datetime(2015, 8, 3, 8, 50, 10, 152110),
  u'msg_id': u'ddaf08b9-02e3-47a6-8e08-45bd519f79b8',
  u'msg_type': u'execute_request',
  u'session': u'5c784d01-74e0-4831-8753-957b8205b217',
  u'username': u'user',
  u'version': u'5.0'}}

In [19]: kc.get_iopub_msg(timeout=5)
---------------------------------------------------------------------------
Empty                                     Traceback (most recent call last)
<ipython-input-19-c75f27ab609f> in <module>()
----> 1 kc.get_iopub_msg(timeout=5)

/home/user/anaconda/lib/python2.7/site-packages/IPython/kernel/client.pyc in get_iopub_msg(self, *args, **kwargs)
     82     def get_iopub_msg(self, *args, **kwargs):
     83         ""Get a message from the iopub channel""
---> 84         return self.iopub_channel.get_msg(*args, **kwargs)
     85
     86     def get_stdin_msg(self, *args, **kwargs):

/home/user/anaconda/lib/python2.7/site-packages/IPython/kernel/blocking/channels.pyc in get_msg(self, block, timeout)
     55             return self._recv()
     56         else:
---> 57             raise Empty
     58
     59     def get_msgs(self):

Empty:
```

Others dataframes are working as expected. 

The R interpreter works correctly:

```
flight origin dest air_time distance hour minute
1        1545    EWR  IAH      227     1400    5     17
2        1714    LGA  IAH      227     1416    5     33
3        1141    JFK  MIA      160     1089    5     42
4         725    JFK  BQN      183     1576    5     44
5         461    LGA  ATL      116      762    5     54
6        1696    EWR  ORD      150      719    5     54
7         507    EWR  FLL      158     1065    5     55
8        5708    LGA  IAD       53      229    5     57
9          79    JFK  MCO      140      944    5     57
10        301    LGA  ORD      138      733    5     58
...
```

I tried this on Ubuntu 15.04, after reinstalling IR kernel and using R version 3.2.1.

**Comment by takluyver** [comment] 2015-08-03 18:16
How big is the data frame? I would guess one of the repr methods is trying to display the whole thing, and that's taking a long time. @flying-sheep , does that sound plausible?

**Comment by rsmith31415** [comment] 2015-08-03 19:11
Reasonably big:

```
> data(flights)
> dim(flights)
[1] 336776     16
```

Maybe that's the problem (particularly, the HTML and LaTeX representations because dput is very fast) I still tried to let the computer running for 30 minutes or so and didn't finish. Probably something doesn't scale well. Another thing I noticed is that loading dplyr changes the output to something similar to `head(flights)`. That's not the case using the IRkernel.

**Comment by flying-sheep** [comment] 2015-08-03 20:30
ouch. yeah, repr could *really* use some “repr.matrix.maxcols/rows”

**Comment by takluyver** [comment] 2015-08-03 20:45
I had a feeling that might be the case ;-). There's similar code in pandas, feel free to draw inspiration from that.

**Comment by flying-sheep** [comment] 2015-08-06 15:38
fixed in Irkernel/repr@a04be61363e8b8255a0bc1420c7707679f80791e

**Comment by flying-sheep** [comment] 2015-08-06 15:39
drew inspiration from pandas’ defaults

**Closed by flying-sheep** 2015-08-06 15:38 UTC

**Comment by rsmith31415** [comment] 2015-08-06 18:50
Are you sure you can install the updated version by using:

```
library(devtools)
# Install the packages
install_github('IRkernel/repr')
install_github('IRkernel/IRdisplay')
install_github('IRkernel/IRkernel')
# Install the kernel spec
IRkernel::installspec()
```
I get this error:

```
[E 13:43:28.755 NotebookApp] Failed to load kernel spec: 'ir'
    Traceback (most recent call last):
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/html/services/kernelspecs/handlers.py", line 56, in get
        d = kernelspec_model(self, kernel_name)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/html/services/kernelspecs/handlers.py", line 19, in kernelspec_model
        spec = ksm.get_kernel_spec(name)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/kernel/kernelspec.py", line 159, in get_kernel_spec
        return KernelSpec.from_resource_dir(resource_dir)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/kernel/kernelspec.py", line 53, in from_resource_dir
        return cls(resource_dir=resource_dir, **kernel_dict)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 565, in __init__
        setattr(self, key, value)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 430, in __set__
        new_value = self._validate(obj, value)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 451, in _validate
        return self.validate(obj, value)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 1267, in validate
        self.error(obj, value)
      File "/home/user/anaconda/envs/jupyter-notebook/lib/python2.7/site-packages/IPython/utils/traitlets.py", line 480, in error
        raise TraitError(e)
    TraitError: The 'display_name' trait of a KernelSpec instance must be a unicode string, but a value of [u'R'] <type 'list'> was specified.
```

After installing the snapshot packages and only update the `repr` package, I was able to test the changes, but there are some display issues (e.g. `data.frame(x=1:100)`), however, I'm not sure if those are caused by the installation errors.

**Comment by takluyver** [comment] 2015-08-06 18:56
Rats, I bet that's a consequence of #173

**Comment by takluyver** [comment] 2015-08-06 19:03
OK, kernelspec install should be fixed now.

**Comment by rsmith31415** [comment] 2015-08-06 19:09
Great. Thanks.

 There are still display issues, though:

![screenshot from 2015-08-06 14 07 28](https://cloud.githubusercontent.com/assets/599274/9120879/8b74fdea-3c44-11e5-92dc-9bef06058573.png)

**Comment by flying-sheep** [comment] 2015-08-06 21:04
could you give me some standalone code to reproduce that?

**Comment by rsmith31415** [comment] 2015-08-06 21:47
I'm not sure what you mean. If you try to evaluate `data.frame(x=1:100)`, don't you get the same result as in the image above? By the way, multidimensional dataframes work okay.

**Comment by flying-sheep** [comment] 2015-08-07 05:31
fixed in IRkernel/repr@b9a550c0668b70cb516d74f4e9477976deb31242

**Comment by rsmith31415** [comment] 2015-08-07 19:11
Excellent. That fixes data frames. What about matrix? 

![screenshot from 2015-08-07 14 06 10](https://cloud.githubusercontent.com/assets/599274/9143701/7eb774b0-3d0d-11e5-8c35-233b4d9ce52e.png)

![screenshot from 2015-08-07 14 10 18](https://cloud.githubusercontent.com/assets/599274/9143796/10199a50-3d0e-11e5-81da-a0dc07c46a78.png)

**Comment by flying-sheep** [comment] 2015-08-07 20:05
goddammit :disappointed:

**Comment by rsmith31415** [comment] 2015-08-23 19:17
@flying-sheep Did you figure this out? Should I open another report for this matrix representation issue?

**Comment by flying-sheep** [comment] 2015-08-23 19:48
no idea why this is…

**Comment by rsmith31415** [comment] 2015-08-23 21:49
@flying-sheep Are you absolutely sure that the code is calling the function you modified (`ellip.limit.arr`)? I tried that function independently in both examples (`matrix(1:100)` and `matrix(1:100, nrow=2, ncol=50)`) and worked as expected.

**Comment by flying-sheep** [comment] 2015-08-24 07:18
eh, wait a second. i just assumed there would be a problem since you said it, but looking at the screenshot it actually looks fine.

**Comment by rsmith31415** [comment] 2015-08-26 23:32
@flying-sheep What do you mean? Do you get the correct HTML representation when you tested? Because the last screenshot certainly doesn't look okay.

Here you can see that the output needs to have its index, similar to the DataFrame representation that is now working correctly:

![screenshot from 2015-08-26 18 27 05](https://cloud.githubusercontent.com/assets/599274/9509001/9cb1aad6-4c20-11e5-90ac-6204ed38c9d3.png)

![screenshot from 2015-08-26 18 27 30](https://cloud.githubusercontent.com/assets/599274/9509005/a1d8b644-4c20-11e5-983b-6ef635004daf.png)

**Comment by flying-sheep** [comment] 2015-08-27 07:31
ah! you want the matrix to have row/col indices. i filed IRkernel/repr#14 for this

**Comment by rsmith31415** [comment] 2015-08-27 14:21
I'm not sure if this happened before but that's right. Thanks.

**Comment by flying-sheep** [comment] 2015-08-27 15:13
huh? what happened or didn’t happen? i r confus

**Comment by rsmith31415** [comment] 2015-08-27 21:42
Sorry. I was referring to the issue with the HTML representation of `matrix`. I'm not sure if that is an issue that went unnoticed for a while.
