### ISSUE TITLE
Unable to print in  loop simultaneously

### ISSUE THREAD

**Issue by liqg** [IRkernel/IRkernel#453] opened 2017-03-22 10:51 UTC
Help!

`for(i in 1:11){print(i); Sys.sleep(1)}`

This will print all after  finished, but I want to print information simultaneously, which is helpful for a long-time loop.

Thanks!

**Comment by flying-sheep** [comment] 2017-03-22 11:02
duplicate of #3

**Closed by flying-sheep** 2017-03-22 11:02 UTC

**Comment by liqg** [comment] 2017-03-23 01:59
@flying-sheep Thank you very much! I am sorry for not checking history carefully!

**Comment by flying-sheep** [comment] 2017-03-23 09:33
no problem 😄
