### ISSUE TITLE
Rendering of graphs in R kernel Notebooks on GitHub

### ISSUE THREAD

**Issue by cfljam** [IRkernel/IRkernel#145] opened 2015-06-01 15:07 UTC
Hi
I have been making some example notebooks about use of the kernel and R2Py for R authoring in Jupyter but have struck some inconsistencies in notebook rendering on GitHub. 

Whereas my python kernel notebook using R2py displays fine https://github.com/cfljam/pyRat/blob/master/Notebooks/Using%20R2Py%20in%20Jupyter%20NOtebooks.ipynb

but the same code using IRKernel doesnt display them https://github.com/cfljam/pyRat/blob/master/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb

My apologies  if this is off-topic and should direct this to Github but I would be grateful of any suggestions. The automatic rendering of Jupyter notebooks in GitHub is a huge attraction and so a major motivation for using this kernel.

**Comment by rgbkrk** [comment] 2015-06-01 16:11
Interesting. It doesn't render on nbviewer either. http://nbviewer.ipython.org/github/cfljam/pyRat/blob/master/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb

I do see the plots in the raw notebook (5 different display options!!!).

**Comment by takluyver** [comment] 2015-06-01 16:50
Sounds like jupyter/nbconvert#5. Kyle, do you know what version of nbconvert is running on nbviewer (& Github's renderer)?

**Comment by cfljam** [comment] 2015-06-01 21:12
I have also struck some similar cases of missing textual output from %%bash cell magics when rendered with nbviewer. I will try to find a reproducible example of this.

Many thanks for looking into this...predictable rendering of content would make the R kernel+ Jupyter  a **very** attractive  alternative to Rmd.

**Comment by rgbkrk** [comment] 2015-06-02 01:37
Always latest release since last merged PR/deploy, which appears to be 5 days ago (via breadcrumbs at the bottom of any nbviewer page).

**Comment by cfljam** [comment] 2015-06-02 06:13
Exactly the same result (ie missing images) rendered with
````
root@940e5f39d03b:/Users/johnmccallum/Documents/pyRat/Notebooks# ipython nbconvert --version
3.2.0-dev
```

**Comment by flying-sheep** [comment] 2015-06-02 15:08
well, the fix was in *Jupyter* nbconvert. IPython nbconvert still has the bug.

the 5 display options are overkill, but the amount of bugs we discovered in several IPython/Jupyter components by leaving it in is worth it imho. (although we could remove JPEG, which leaves PNG, SVG, PDF, and the dummy text output)

**Comment by takluyver** [comment] 2015-06-02 18:08
Yeah, I doubt JPEG is worth it - anything that can create or consume JPEG can presumably create or consume PNG as well.

I'll backport jupyter/nbconvert#5 to ipython.

**Comment by takluyver** [comment] 2015-06-02 18:13
ipython/ipython#8501 should do the trick

**Comment by rgbkrk** [comment] 2015-06-02 21:02
Personally, I wouldn't leave PDF in. The bigger the notebooks get, the less likely they're viewable on nbviewer, github, etc.

**Comment by flying-sheep** [comment] 2015-06-02 21:30
well, PDF is perfect for latex output.

and in my institute it’s the format that’s most used for plots that get sent around.

**Comment by cfljam** [comment] 2015-06-17 03:05
Thanks for the help on this. I'm not quite sure if this is the same matter but I am finding that any notebooks with images generated by the R kernel get hugely bloated- even a single figure make the notebooks too big for nbviewer to handle as @rgbkrk notes. I have some reproducible evidence at http://nbviewer.ipython.org/gist/cfljam/674ad20caab81de32598

**Comment by rgbkrk** [comment] 2015-06-17 03:21
Yup, that's because the R kernel defaults to displaying every mimetype and the notebook server captures *all* of them in the notebook...

**Comment by cfljam** [comment] 2015-06-17 03:43
Thanks for that. This seems like it  limits  usability of Rkernel notebooks in terms of Github/Gist workflows, so I will stick with the RPy2 until this changes.

**Comment by rgbkrk** [comment] 2015-06-17 03:54
If I had to guess, it's the SVG output that is the largest of the whole lot, especially with that test case. I'll do some testing and report back.

**Comment by rgbkrk** [comment] 2015-06-17 04:45
Fast and loose reading of a notebook with the little ggplot diamonds example:

```
In [79]: nb = json.load(open("test.nb"))

In [80]: cell = nb['cells'][0]

In [82]: cell['source']
Out[82]:
[u'library(ggplot2)\n',
 u'ggplot(diamonds,aes(x=carat,y=price)) + geom_jitter(aes(color=cut))']

In [83]: display_data = cell['outputs'][1]['data']

In [84]: {k: humanize.naturalsize(len(v)) for (k,v) in display_data.items()}
Out[84]:
{u'application/pdf': '2.0 MB',
 u'image/jpeg': '152.3 kB',
 u'image/png': '47.4 kB',
 u'image/svg+xml': '54.3 kB'}
```

The application/pdf serialized is taking up a whopping 2.0 MB.

**Comment by flying-sheep** [comment] 2015-06-17 08:56
also interesting that SVG is almost as small as PNG.

to circumvent the issue, you can simply do `options(jupyter.plot_mimetypes = "image/svg+xml")`

**Comment by takluyver** [comment] 2015-06-17 17:53
@flying-sheep given the numbers @rgbkrk showed, I think we should consider leaving PDF out by default. It's easy enough for people who want it to re-enable it, but I think optimising for the web is higher priority for the defaults than optimising for Latex.

**Comment by flying-sheep** [comment] 2015-06-17 18:11
Let's keep PNG and SVG, OK?

**Comment by takluyver** [comment] 2015-06-17 18:16
:+1:

**Comment by cfljam** [comment] 2015-06-17 19:12
Thanks for the options tip ...@flying-sheep  sensible web payloads now

**Before**
```
johns-mbp:Notebooks johnmccallum$ ls -lh
total 68568
-rw-r--r--  1 johnmccallum  staff    33M  2 Jun 02:39 Jupyter Notebooks with the R kernel.ipynb
-rw-r--r--  1 johnmccallum  staff    26K  2 Jun 02:34 Using R2Py in Jupyter NOtebooks.ipynb
```
**After** using options(jupyter.plot_mimetypes = 'image/png')
```
johns-mbp:Notebooks johnmccallum$ ls -lh
total 800
-rw-r--r--  1 johnmccallum  staff   167K 18 Jun 07:03 Jupyter Notebooks with the R kernel.ipynb
-rw-r--r--  1 johnmccallum  staff    26K  2 Jun 02:34 Using R2Py in Jupyter NOtebooks.ipynb
```

**Comment by takluyver** [comment] 2015-06-17 22:34
#154 takes pdf and jpeg out of the default values.

I try to fix all issues in a PR whose number is an anagram of the issue number. ;-)

**Comment by flying-sheep** [comment] 2015-06-18 12:16
i merged it, but IDK if this will be fixed by it.

we have to check if `application/pdf`, `image/svg+xml` or something completely different breaks on github.

(or they have to but hey still didn’t investigate)

**Comment by jonrobinson2** [comment] 2015-07-14 04:09
So I don't think this is fixed. Example of where the graphics aren't rendered in  the Github rendering of the ipynb is here:

https://github.com/jonrobinson2/teaching_R_material/blob/master/Brad's%20Variance-Covariance%20Matrix%20Stuff.ipynb

and over here is the nbviewer version of that file which renders the base graprhic image but totally butchers the ggplot graphic.

http://nbviewer.ipython.org/github/jonrobinson2/teaching_R_material/blob/master/Brad's%20Variance-Covariance%20Matrix%20Stuff.ipynb

**Comment by flying-sheep** [comment] 2015-07-14 10:09
no it isn’t, but we can’t do more than to bug github to fix it on their side :neutral_face:

**Comment by jonrobinson2** [comment] 2015-07-14 11:32
:-1:

**Comment by flying-sheep** [comment] 2015-07-14 13:06
maybe if more people sen them mails than just me it would help? or maybe they just get annoyed.

they just need to update IPython to 3.2.1…

**Comment by jonrobinson2** [comment] 2015-07-14 13:59
I tweeted at Fernando. 

https://twitter.com/jon_m_rob/status/620918424072400897

Any idea though why the nbconvert is messing around with the font type on my ggplot2 graph in the link above?

**Comment by flying-sheep** [comment] 2015-07-15 07:59
no, that has to do with #128, i.e. it has been fixed in 34eacbe82bd8221b110f96bfb8c50c8be4d64ebb

if nbviewer respects the `isolate` flag, rerunning the notebook with a IRKernel version after that commit (i think 0.4 has it) will fix it. if it doesn’t support that flag, it needs to implement it or we need to change the output of cairo’s svg rendering.

**Comment by ethanwhite** [comment] 2015-07-23 19:06
> maybe if more people sen them mails than just me it would help? or maybe they just get annoyed.
> they just need to update IPython to 3.2.1…
> except if they strip out SVGs, then they also need to fix that.

@arfon - any chance of getting the nbconvert version upgraded so that images in R-based notebooks will display properly on GitHub?

**Comment by arfon** [comment] 2015-07-23 19:13
Thanks for looping me in on the discussion @ethanwhite.

Getting up to speed on the thread I think there are two things going on here:

1. If we upgraded our nbconvert then we would get R notebooks rendering too?
2. SVGs are still causing some issues for people?<sup>1</sup>

Is that a fair summary?

1. Note SVGs used to be stripped from the nbconvert output but this was fixed a while ago, see for example [this notebook](https://github.com/wallinm1/vaalikone-text-mining/blob/64b743828b8c2ff91a6ef98c80b7907b2069fada/Ylen_Vaalikone_2015.ipynb))

**Comment by flying-sheep** [comment] 2015-07-24 07:58
hmm, your linked notebook shows that SVGs are handled via `<img src="data:...">`, right? that should already eliminate the problem. the problem should only occur if we embed SVG nodes inline.

the problem is pretty simple, and independent from R. it comes from the way id references are handled in the browser, and the R-emitted SVGs using those.

1. R uses cairo for SVGs
2. cairo-emitted SVGs use [`<symbol/>`s](https://developer.mozilla.org/de/docs/Web/SVG/Element/symbol) for text, i.e. all glyphs are defined once and reused wherever needed instead of either relying on the SVG renderer to render the text (using `<text/>`) or duplicating the glyph paths.
3. if such an SVG is embedded inline, firefox has problems. maybe due to this:

	```html
	<body>
		<svg>
			<defs><symbol id="a">...</symbol></defs>
			...
		</svg>
		<svg>
			<defs><symbol id="a">...</symbol></defs>
			<!-- will this use the first sybol#a or the second? -->
			<use xlink:href="#a" />
		</svg>
	</body>
	```

4. if the  SVG  is in an `<iframe>` or linked to in an `<img>, there should be no problem.

**Comment by arfon** [comment] 2015-07-24 11:20
OK thanks for the detailed feedback @flying-sheep. I'm afraid I just don't have the expertise in either IRkernel, Jupyter/IPython, nbviewer or the way that we've implemented this in GitHub.

Would you mind emailing support@github.com with links pointing to example outputs on NBviewer and GitHub and where they differ? That way the GitHub Render team (the folks that implemented this on GitHub) can be brought into the discussion.

**Comment by flying-sheep** [comment] 2015-07-24 12:14
sure, but i already did that, waited, and after weeks is started nagging about progress, which only resulted in responses of the type “i’ve notified the team, please stand back and wait”.

do i have to mention something specific to get a different result?

anyway, here’s a test if the remaining bug is fixed:

```python
from IPython.nbconvert.exporters import HTMLExporter
priority = HTMLExporter().config.NbConvertBase.display_data_priority
assert 'application/pdf' not in priority
```

the fix is in jupyter/nbconvert@14b13c6b2e586da9c99a4a4e6418051875c371ba and (backported) in ipython/ipython|5ada0da90d1242a548ac217ffb0ea1623ef1a688

**Comment by arfon** [comment] 2015-07-24 12:17
Ah OK, thanks for doing this already. The Render team is pretty small and they're fixing issues in the GitHub nbviewer implementation daily so we might just have to wait a little longer sorry.

**Comment by flying-sheep** [comment] 2015-07-24 13:26
it’s OK, but i doubt there will be an answer, as 

1. sent request end of april/start of may
2. got answer on may 9th: “we asked the team to check it out”
3. asked again on june 2nd 
4. got answer the next day: “we asked the team again”

i think asking again will result in another “we asked the team, pls wait some more” :laughing:

**Comment by sshirokov** [comment] 2015-07-27 23:00
> i think asking again will result in another “we asked the team, pls wait some more”

Hi. I'm part of "the team", sorry for the delays. 

I've upgraded us to ipython-3.2.1, and I'll be looking into the reason we're missing the SVG in that rendering.

> hmm, your linked notebook shows that SVGs are handled via <img src="data:...">, right? that should already eliminate the problem. the problem should only occur if we embed SVG nodes inline.

We do this to notebooks on GitHub that include inline SVG images for security reasons. If you decode the body you'll find the original SVG document from the conversion.

I'll take a closer look at the `jonrobinson2/teaching_R_material` notebook's SVG handling to see if there's an issue we can resolve.

> but the same code using IRKernel doesnt display them https://github.com/cfljam/pyRat/blob/master/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb

This notebook contains merge conflicts at the time of writing :crying_cat_face: Check out the `Raw` view on the current master revision (9e91bf618a0e3)(https://raw.githubusercontent.com/cfljam/pyRat/9e91bf618a0e3324651cf9adabae22c1625f41fd/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb) 

The previously mentioned revision in the merge conflict renders, though: https://github.com/cfljam/pyRat/blob/13024ee143030d8ab973547c436ea237aad8f331/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb

Thank you for the feedback.

**Comment by flying-sheep** [comment] 2015-07-28 07:42
that revision only has PNGs in it.

[here’s a revision with SVGs, PDFs, and whatnot](https://github.com/cfljam/pyRat/blob/d2a338ae0d2f9c2e549a604871b62229a35f8552/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb). it doesn’t render.

**Comment by sshirokov** [comment] 2015-07-30 00:37
> of course that revision renders as it only has PNGs in it.

:blush: woops

> here’s a revision with SVGs, PDFs, and whatnot. it doesn’t render properly, the plots are omitted.

Unfortunately, that notebook is >34MB and explodes significantly in resident size during our processing, so until a few things change it's staying broken :disappointed: 

On the bright side, [this previously broken](https://github.com/jonrobinson2/teaching_R_material/blob/0d12484092974da836ea130f65e22ea0148d6924/Brad's%20Variance-Covariance%20Matrix%20Stuff.ipynb) notebook now works, since we fixed up our `display_data_priority`. 

Thanks for your help and patience.

**Comment by jonrobinson2** [comment] 2015-07-30 00:50
Awesome!

**Comment by ethanwhite** [comment] 2015-07-30 00:59
This fixed my issues as well. Thanks @sshirokov & @arfon!

**Comment by flying-sheep** [comment] 2015-07-30 07:53
Thanks @sshirokov! That `display_data_priority` fix was all that was still needed :fireworks: 

the one you linked also has PDFs in it, and now displays, so it’s the same bug!

@cfljam this is now fixed. once you resolve the merge conflicts in [this notebook](https://github.com/cfljam/pyRat/blob/master/Notebooks/Jupyter%20Notebooks%20with%20the%20R%20kernel.ipynb), you should be able to remove the `options(jupyter.plot_mimetypes = 'image/png')` line, rerun the notebook, and it should still display fine!

**Closed by flying-sheep** 2015-07-30 07:53 UTC

**Comment by cfljam** [comment] 2015-07-30 21:00
My apologies for the conflicted notebook and thanks for all the work! 

Repaired notebook renders fine at gist.github.com  without options

https://gist.github.com/cfljam/c37b94366953f0320c38

**Comment by flying-sheep** [comment] 2015-07-31 07:45
why does that notebook only have PNGs in it? i don’t see you overriding the mime types…

did you create the plots in a session where you set the mimetypes to only PNG, and then remove the cell with the `options()` call in it?
