### ISSUE TITLE
kernel freeze after loading R object

### ISSUE THREAD

**Issue by pinshuai** [IRkernel/IRkernel#571] opened 2018-06-19 00:08 UTC
I am trying to execute R script in Jupyter. However, whenever I try the `load("data.rda")` function, the kernel seems to freeze (busy all the time). Is it because my R object file is too big (around 1 GB)?

R version 3.5.0 (2018-04-23) -- installed from R cran
Ipython version 6.1.0 -- installed from Anaconda

I am running on macOS High Sierra (V 10.13.5).

Any help would be appreciated!

**Comment by flying-sheep** [comment] 2018-06-19 11:00
it should work exactly the same as in R or RStudio.

if it really only happens in the IRkernel: can you upload the data somewhere so i can try to reproduce it?

**Comment by pshuai88** [comment] 2018-06-19 18:53
I created a test dataset for you [here](https://www.dropbox.com/s/9xkgl3d493g89qj/test.r?dl=0). 

I can load this kind of data without problem in Rstudio. But in Jupyter, this took forever. 

Thanks!

**Comment by takluyver** [comment] 2018-06-19 19:02
If you're just doing `load("data.rda")` without assigning it, it may be loading it and then immediately trying to display it. Perhaps the display step is what's slow.

**Comment by pshuai88** [comment] 2018-06-19 21:10
Hi @takluyver , I tired assigning R object to a variable. The kernel still running slow.

The following warning displayed in the terminal:

> The notebook server will temporarily stop sending output to the client in order to avoid crashing it.
To change this limit, set the config variable
    `--NotebookApp.iopub_data_rate_limit`.`
       Current values:
    NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
    NotebookApp.rate_limit_window=3.0 (secs)

I increased the rate limit by `jupyter notebook --NotebookApp.iopub_data_rate_limit=10000000000` as mentioned in [#2287](https://github.com/jupyter/notebook/issues/2287). But the kernel still freeze after loading R object.

**Comment by takluyver** [comment] 2018-06-20 08:27
Thinking about it, I think R shows the value even when you assign it.

The fact that you're getting a warning about rate limiting output supports my theory that the problem is with displaying the data rather than loading it. If it's getting slow as it tries to produce large amounts of output, increasing the rate limit will probably make things worse rather than better.

**Comment by flying-sheep** [comment] 2018-06-20 08:40
Hmm, the documentation says that even with `verbose = TRUE`, only the names of the loaded variables are printed: http://stat.ethz.ch/R-manual/R-devel/library/base/html/load.html

**Comment by pshuai88** [comment] 2018-06-20 18:47
@takluyver I tried load() with a small R object (< 1 MB) and jupyter could load within second.  Also, there was no output printed. So I do not think it was the output issue.

**Comment by takluyver** [comment] 2018-06-20 18:55
OK, maybe I was wrong. Though the warning about "will temporarily stop sending output" suggests that something was sending a large amount of output.

**Comment by Seviks** [comment] 2019-08-30 07:59
Similar problem here:
In JupyterLab if using readRDS the kernel keeps busy after loading the file. The number for the codeblock is there. There is also siginificant CPU load. 

Code like this does not show output:
data<- readRDS("data.rds")

This happens only with JupyterLab! With Jupyter Notebbok it works. 

R 3.6.1
JupyterLab 1.0.9
Windows 10

**Comment by flying-sheep** [comment] 2019-09-03 09:01
can you try to use [profvis](https://rstudio.github.io/profvis/) to figure out what’s happening?

**Comment by Seviks** [comment] 2019-09-04 07:49
I tried:
```
profvis(
     a <- readRDS("data.rds")
)
```
The result pops up after a second and the cell changes from * to an number. Afterwards the kernel stays busy. The result from provis that pops up fast: 
![grafik](https://user-images.githubusercontent.com/4014268/64235635-0fdf9400-cef9-11e9-93d7-c46e384405d9.png)

Please tell me if I can provide more info to debug.

**Comment by flying-sheep** [comment] 2019-09-04 09:52
huh, weird! so the actual readRDS finishes quickly …

I’ll look into it.

**Comment by jmdc-dkanazawa** [comment] 2019-12-13 07:27
I had the same problem of Seviks.
However, it solved after removing labextension 'jupyterlab_variableinspector'.
I hope it'll help you. Thank you.

**Comment by flying-sheep** [comment] 2019-12-13 11:08
Well, first of all I’m amazed that the variable inspector works with our kernel, pretty cool.

It works by defining the functions `.ls.objects` and `.deleteVariable`. If the inspector is the problem, the problem might be due to the former being called on some large object?

**Comment by flying-sheep** [comment] 2019-12-13 11:42
I filed lckr/jupyterlab-variableInspector#122

**Comment by jmdc-dkanazawa** [comment] 2019-12-16 05:28
> It works by defining the functions `.ls.objects` and `.deleteVariable`. If the inspector is the problem, the problem might be due to the former being called on some large object?

I think so. We reproduce this problem using 'iris' dataset.
1. It took about 10secs to run code below.
```
start.time <- Sys.time()
{myiris <- bind_rows(replicate(1000, iris, simplify=F)); NULL}
dim(myiris)
```
and jupyter-lab output and log are as follows.
```
NULL
1. 150000
2. 5
```
```
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: start.time <- Sys.time()
{myiris <- bind_rows(replicate(1000, iris, simplify=F)); NULL}
dim(myiris)
DEBUG: Value output...
DEBUG: Value output...
DEBUG: Sending display_data: List of 1
 $ text/plain: chr "NULL"
DEBUG: Sending msg display_data
DEBUG: Value output...
DEBUG: Sending display_data: List of 4
 $ text/html    : chr "<ol class=list-inline>\n\t<li>150000</li>\n\t<li>5</li>\n</ol>\n"
 $ text/markdown: chr "1. 150000\n2. 5\n\n\n"
 $ text/latex   : chr "\\begin{enumerate*}\n\\item 150000\n\\item 5\n\\end{enumerate*}\n"
 $ text/plain   : chr "[1] 150000      5"
DEBUG: Sending msg display_data
DEBUG: Sending msg execute_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
DEBUG: main loop: after poll. ZMQ code: 1; Errno: 11
DEBUG: main loop: shell
DEBUG: Sending msg status
DEBUG: Sending msg execute_input
DEBUG: Executing code: .ls.objects()
DEBUG: Stream output:      varType varSize     varShape
1   function   21912     1  x  NA
2   function    2472     1  x  NA
3   function   14504     1  x  NA
4   function    1904     1  x  NA
5   function    2480     1  x  NA
6 data.frame 5401856 150000  x  5
7   function    4088     1  x  NA
8    POSIXct     344     1  x  NA
9   function  137520     1  x  NA
                                                                    varContent
1                                          function (fit, standardized = TRUE)
2                                            function (..., deparse.level = 2)
3                                                          function (x, n = 6)
4                                function (x, n = 60, ncol = 10, byrow = TRUE)
5                                                               function (str)
6 Column names:  Sepal.Length, Sepal.Width, Petal.Length, Petal.Width, Species
7                                                      function (actual, pred)
8                                                          2019-12-16 14:17:57
9                            function (object, digits = 3, latex = FALSE, ...)
  isMatrix            varName
1    FALSE   bob3_lavaan_plot
2    FALSE         crossTable
3    FALSE              mhead
4    FALSE             mxhead
5    FALSE    myDisplayModify
6    FALSE             myiris
7    FALSE                RSQ
8    FALSE         start.time
9    FALSE summary.CrossTable

DEBUG: Sending msg stream
DEBUG: Value output...
DEBUG: Sending display_data: List of 1
 $ text/plain: chr "[{\"varType\":\"function\",\"varSize\":21912,\"varShape\":\"1  x  NA\",\"varContent\":\"function (fit, standard"| __truncated__
DEBUG: Sending msg display_data
DEBUG: Sending msg execute_reply
DEBUG: Sending msg status
DEBUG: main loop: beginning
```

2. It took about 3 minutes when replicate counts up to 10,000.
```
{myiris <- bind_rows(replicate(10000, iris, simplify=F)); NULL}
```

**Comment by flying-sheep** [comment] 2019-12-16 09:36
Please continue discussing this in lckr/jupyterlab-variableInspector#122

**Closed** 2022-04-13 08:09 UTC
Labels: upstream bug
