### ISSUE TITLE
CairoPDF can't save 2 hist plot in jupyter while this works well in Rstudio

### ISSUE THREAD

**Issue by DawnEve** [IRkernel/IRkernel#658] opened 2020-05-18 09:40 UTC
this can woks well in Rstudio, while in Jupyter'R page, it saves well with one hist plot, 
but  saves nothing(0 B) when 2 hist plot are sued.
In short, I can't get pdf file with the following code in Jupyter with IRKernel.

```
library(Cairo)
CairoPDF('test.pdf', width=5, height=4)
hist(mtcars$mpg, main="1")
hist(mtcars$mpg, main="2")
dev.off()
```

I'm not sure it's the jupyter notebook or IRkernel 's problem.

**Comment by flying-sheep** [comment] 2020-05-19 13:26
can you try doing `dev.off()` before `CairoPDF(...)`?

I’m using a cairo device as internal device, maybe Cairo has a bug that you can’t have nested devices.

**Comment by DawnEve** [comment] 2020-05-21 03:42
> can you try doing `dev.off()` before `CairoPDF(...)`?
> 
> I’m using a cairo device as internal device, maybe Cairo has a bug that you can’t have nested devices.

this realy works! thank you

**Comment by flying-sheep** [comment] 2020-05-26 13:32
great! hmm, I think this can be marked as a duplicate of #168 then.

**Closed by flying-sheep** 2020-05-26 13:32 UTC
