### ISSUE TITLE
xcrun and pbdZMQ error on mac with R-3.4.1

### ISSUE THREAD

**Issue by piyushm08** [IRkernel/IRkernel#511] opened 2017-10-13 05:12 UTC
```r
> devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/yw/drrbc7w906g9mt5lhh41zfgm0000gn/T/Rtmp9udVuk/devtools312b78f37053/IRkernel-IRkernel-5f8ac38'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘IRkernel’ ...
Warning in as.POSIXlt.POSIXct(x, tz) :
  unknown timezone 'default/Australia/Melbourne'
** R
** inst
** tests
** preparing package for lazy loading
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Warning: running command '/usr/bin/otool -L /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pbdZMQ/libs/pbdZMQ.so' had status 1
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (org != fn.libzmq.4.dylib) {
  error: missing value where TRUE/FALSE needed
ERROR: lazy loading failed for package ‘IRkernel’
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/IRkernel’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 
```

**Comment by flying-sheep** [comment] 2017-10-16 09:23
dupe of #490

**Closed by flying-sheep** 2017-10-16 09:23 UTC
