### ISSUE TITLE
Error installing IRkernel

### ISSUE THREAD

**Issue by annu025** [IRkernel/IRkernel#516] opened 2017-10-22 08:53 UTC
I am getting the below error:

```r
> devtools::install_github('IRkernel/IRkernel')`

Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
'/Library/Frameworks/R.framework/Resources/bin/R' --no-site-file  \
  --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/7s/7t2s0lmn4yx39d45ck75c_y80000gn/T/Rtmp8hUGIm/devtools13fde8bd847/IRkernel-IRkernel-49b2eb2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.4/Resources/library'  \
  --install-tests 

* installing *source* package ‘IRkernel’ ...
** R
** inst
** tests
** preparing package for lazy loading
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Warning: running command '/usr/bin/otool -L /Library/Frameworks/R.framework/Versions/3.4/Resources/library/pbdZMQ/libs/pbdZMQ.so' had status 1
Error : .onLoad failed in loadNamespace() for 'pbdZMQ', details:
  call: if (org != fn.libzmq.4.dylib) {
  error: missing value where TRUE/FALSE needed
ERROR: lazy loading failed for package ‘IRkernel’
Installation failed: Command failed (1)
Warning message:
GitHub repo contains submodules, may not function as expected! 
* removing ‘/Library/Frameworks/R.framework/Versions/3.4/Resources/library/IRkernel’
```

Please suggest what needs to be done. 
Thanks.

**Comment by flying-sheep** [comment] 2017-10-23 08:06
dupe of #490

**Closed by flying-sheep** 2017-10-23 08:06 UTC
