### ISSUE TITLE
No renderer could be found for output. It  has the following MIME types

### ISSUE THREAD

**Issue by raivivek** [IRkernel/IRkernel#597] opened 2018-11-13 18:14 UTC
Whenever I make plots, I get the following message:
```
No renderer could be found for output. It has the following MIME types:
<plot here>
```

I am running Jupyterlab in interactive environment with latest version of IRKernel. The reason I'm particularly concerned about the message is because the resulting plot, is alright in typical sense, has very poor fonts. For example (note the fonts),

![image](https://user-images.githubusercontent.com/3218617/48433736-e412d800-e745-11e8-8d5b-b447b54445f2.png)

And how it appears if I use different version of R (where I do not get this message):

![image](https://user-images.githubusercontent.com/3218617/48433768-f725a800-e745-11e8-9c4d-e111e7a5f0f7.png)

I'm running Microsoft R-Open 3.5.1

```
>sessionInfo()
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Debian GNU/Linux 9 (stretch)

Matrix products: default
BLAS: /home/vivekrai/.anaconda3/envs/mro_env/lib/R/lib/libRblas.so
LAPACK: /home/vivekrai/.anaconda3/envs/mro_env/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RevoUtils_11.0.1     RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1

> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
```

**Comment by flying-sheep** [comment] 2018-11-14 10:56
Hi! I have not yet found out why this message appears, I get it too.

I’m very sure that it has nothing to do with the poor fonts. Those might be fixed by `install.packages('Cairo')` (restart the kernel after). Cairo often produces superior plots.

That message seems to come from jupyter, not us. But obviously there *is* a renderer found, else we wouldn’t see a plot… weird.

**Comment by raivivek** [comment] 2018-11-14 18:09
@flying-sheep Hi! I have `Cairo` library installed already, but for some reason, it doesn't fix the font problem! :/

![image](https://user-images.githubusercontent.com/3218617/48502838-84ccca80-e80e-11e8-8118-d2351d9063f3.png)

**Comment by flying-sheep** [comment] 2018-11-14 20:57
No idea, sorry :cry:

**Comment by egnha** [comment] 2018-11-18 07:17
Interestingly, the message (`No renderer could be found for output`) disappears when you explicitly invoke `print()`. For example, I get the message with
```R
ggplot2::ggplot(mtcars)
```
but not with
```R
print(ggplot2::ggplot(mtcars))
```
This suggests to me that the issue is with the repr package, in particular that a `repr_mimebundle()` method should be implemented.

**Comment by egnha** [comment] 2018-11-19 13:00
I notice now that the message also arises when printing other objects, not just plots, for example when invoking `help(package = base)`. (This is under JupyterLab 0.35.3.)

**Comment by robsalasco** [comment] 2018-12-11 16:14
I have the same issue!

**Comment by jbloom** [comment] 2019-01-06 00:37
I am also having this problem.

**Comment by flying-sheep** [comment] 2019-01-07 08:56
@egnha as I wrote most of the code at play here, I can tell you about it.

The difference is that in the first case, all mime types are tried and in the second only the plot mime types, because we use completely different code paths.

`repr` is used in *both cases* of course.

1. If you just put an expression into a cell, `handle_value` is invoked:

    https://github.com/IRkernel/IRkernel/blob/202dc388bd7191b6b165133b46b51d9765bd201d/R/execution.r#L195-L208

    which invokes `prepare_mimebundle_kernel`:

    https://github.com/IRkernel/IRkernel/blob/202dc388bd7191b6b165133b46b51d9765bd201d/R/handlers.r#L1-L18

2. If you use `print`, you invoke `print.ggplot`, which in turn uses `grid.draw`:

    https://github.com/tidyverse/ggplot2/blob/9eae13b3d17bde26cf9df649887b4a6bb2ac92ce/R/plot.r#L168-L172

    Which will trigger `handle_graphics` in IRkernel:

    https://github.com/IRkernel/IRkernel/blob/202dc388bd7191b6b165133b46b51d9765bd201d/R/execution.r#L217-L227

    which delegates to `send_plot`:

    https://github.com/IRkernel/IRkernel/blob/202dc388bd7191b6b165133b46b51d9765bd201d/R/execution.r#L166-L180

**Comment by flying-sheep** [comment] 2019-01-07 09:06
Thinking about it, the code path for plain `ggplot` is different:

1. `handle_value`
2. `repr_text` (and the other `repr_*` functions)
3. `repr_text.default`:

    https://github.com/IRkernel/repr/blob/39516108ae57282fa35a630337ed43d2310dcdd3/R/generics.r#L33-L35

4. `handle_graphics`

this means that there’s probably an empty mime bundle being created since `repr_text.default` returned `character(0)` (with `handle_graphics` creating a *second* mimebundle that’s being displayed.

**Closed** 2019-01-07 09:19 UTC

**Comment by egnha** [comment] 2019-01-07 11:36
@flying-sheep, thanks a lot for the explanation, and the fix!
