### ISSUE TITLE
problem in unicode in R from jupyternotebook

### ISSUE THREAD

**Issue by githubPratima** [IRkernel/IRkernel#730] opened 2023-02-03 16:54 UTC
Your code contains a unicode char which cannot be displayed in your
current locale and R will silently convert it to an escaped form when the
R kernel executes this code. This can lead to subtle errors if you use
such chars to do comparisons. For more information, please see
https://github.com/IRkernel/repr/wiki/Problems-with-unicode-on-windows
Error in parse(text = x, srcfile = src): <text>:12:1: unexpected '<'
11: }
12: <
    ^
Traceback:

**Comment by flying-sheep** [comment] 2023-02-03 19:42
Duplicate of #731

**Closed by flying-sheep** 2023-02-03 19:42 UTC
