### ISSUE TITLE
Possible memory leak with ggplot2 using plotmath

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [IRkernel/IRkernel#291] opened 2016-04-06 12:26 UTC
Hi guys

attached is a minimum example of a notebook that gives me problems in Chrome on Windows 7. 

Basically, this one works:

```r
temp <- paste("Deuterium~D", "[", "alpha", "]")

p <- ggplot() +
    geom_text(aes( 656, 0.5, label = temp), parse=TRUE)

print(p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) )
```

The snippet below works in R-Studio with ~400MB memory consumption. In Jupyter it causes the python process to jump to 1GB and the Chrome associated notebook tab will slowly increase in memory and in the end crash at 4GB. (My total memory is 8GB)

```r
temp <- paste("Deuterium~D", "[", "alpha", "]")

p <- ggplot( data=data, aes(x=x, y=y, group=Sample) ) +
    geom_text(aes( 656, 0.5, label = temp), parse=TRUE)

print(p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) )
```

data is just some random numbers. The full working (i.e. not working ;-) ) example is in the attached notebook. 
Any ideas? Maybe I'm just using ggplot2 in the wrong way?

Best wishes, 
Nikolai

[Memory Leak.zip](https://github.com/IRkernel/IRkernel/files/206370/Memory.Leak.zip)

**Comment by janschulz** [comment] 2016-04-06 12:44
[This is a guess without looking at your example yet]
You don't need to print the plot, you can just let them be printed by the default functionality in the irkernel (or better evaluate).

Just a guess: we draw at least two times: png and svg. It could be that one of the draws is too big for you ram... You can change that by running 

```
options(jupyter.plot_mimetypes = c("image/png" ))
```

**Comment by Nikolai-Hlubek** [comment] 2016-04-06 14:20
Hi Jan. 

Thanks for the comment. Simplyfing to the code below still crashes with the huge memory consumption. When I use your png option it does not memory leak. 

```
temp <- paste("Deuterium~D", "[", "alpha", "]")

ggplot( data=data, aes(x=x, y=y, group=Sample) ) +
    geom_text(aes( 656, 0.5, label = temp), parse=TRUE)
```

The point is, I still think it is a bug, because the data object and the ggplot objects are around 1MB and I do not display any data in my example case just the plotmath label.

When I only plot the data it works. 
When I plot data and label it crashes.

**Comment by janschulz** [comment] 2016-04-10 19:07
I ran the following in rstudio:

```
data <- data.frame()

for (i in 1:10){
  x <- seq(1:4000)
  y <- runif(4000,0.0,1.0)
  yerr <- runif(4000, 0.0, 0.1)
  
  data <- rbind(data, data.frame(x=x, y=y, yerr=yerr, Sample=as.character(i)))
}

head(data)
dim(data)
object.size(data)
library("ggplot2")
temp <- paste("Deuterium~D", "[", "alpha", "]")

p <- ggplot( data=data, aes(x=x, y=y, group=Sample) ) +
  geom_text(aes( 656, 0.5, label = temp), parse=TRUE)
p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) 
ggsave("test.svg")
```

It takes ages and then the produced 53mb big svg file. It contains the label over and over again.

* This looks like a strange artefact on the ggplot side (why is the label printed over and over again) -> maybe report this to the ggplot maintainer?
* Chrome doesn't want to handle a 53MB SVG... Not sure what to do, maybe another plea to remove svg form the default plotting options and use png only (I also can't save svgs, because there is no right click -> save as in chrome...)?

**Comment by janschulz** [comment] 2016-05-06 19:25
I think the problem seems to be that the base `aes` also specifies a `group` and therefore the data which is used in geom_text is blown up to the size of the original dataframe. At least I can make the plotting much faster when I add a `group=1` to the second aes.

**Comment by janschulz** [comment] 2016-05-06 19:59
Note that specifying an empty data.frame in the geom also fixes the problem:

```R
p <- ggplot( data=data) +
  geom_text(aes( 656, 0.5, label = temp), data=data.frame(), parse=TRUE)
p  + coord_cartesian(xlim=c(0,4000), ylim=c(0.0,1.0)) 
p
```

**Comment by janschulz** [comment] 2016-07-08 11:02
Upstream declared this "intended behaviour", so the problem is that ggplot is not expected to be used in this way (e.g. create a df with your values and pass that to `geom_text(aes(...columnnames instead of values...), data=df)`. 

So the problem is a) a really bad edge case and b) that svg is slow in this case. RStudio gets around this because it doesn't use svg and since we removed it, we also now have this fixed.So I'm closing this... 

sorry for not having a better solution but I hope (if you need svg) you can take the workaround by creating the dataframe + using column names.

**Closed by janschulz** 2016-07-08 11:02 UTC
