### ISSUE TITLE
fail to install IRkernel/IRkernel

### ISSUE THREAD

**Issue by LittleBeannie** [IRkernel/IRkernel#592] opened 2018-10-17 15:19 UTC
- hello everyone, I have a problem with install R kernel into Jupyter.  I followed the instruction in https://irkernel.github.io/installation/ and when I run `devtools::install_github('IRkernel/IRkernel')` in Rstudio, it reports that 
Skipping install of 'IRkernel' from a github remote, the SHA1 (97c492b2) has not changed since last install. Use `force = TRUE` to force installation

- And I add `force = TRUE`, it gives a warning message:
Warning message:
GitHub repo contains submodules, may not function as expected! 

- When I run `IRkernel::installspec()`, it gives me a error too:
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 127.
In addition: Warning message:
In system2("jupyter", c("kernelspec", "--version"), FALSE, FALSE) :
  error in running command`

- Could anyone help me fix this problem, I appreciate lots for your warm-hearted help ^_^

**Comment by flying-sheep** [comment] 2018-10-24 16:45
I’ll comment on the four points in order:

- This means that you have the newest version installed!
- You can ignore the warning, the submodules are only used for testing
- That’s the real problem!
- Yup, on it :wink: 

The problem is that you can’t execute `system('jupyter kernelspec --version')`.

You have to be able to do that. please execute `IRkernel::installspec()` only from R started in the console, not in the OSX R app or RStudio or so, that’s a common source of this problem.

**Comment by harishmohan60** [comment] 2018-11-01 04:14
Hi guys, 
I getting the same error for bullet point 3 and tried your solution. But still same error! as you can see in the below image. 
![image](https://user-images.githubusercontent.com/44602129/47832166-c44feb80-ddf8-11e8-85a2-28acde4a3542.png)
Please let me know how to fix this problem!
-----------------------------------------------------
And I got the Jupyter notebook R kernel running with conda but i cant install other packages like 'ggplot2' or 'stringi' (from jupyter notebook ) is this because of the error in IRkernel::installspec()??
------------------------------------------------------

**Comment by ecoquant** [comment] 2018-11-02 13:45
In my case, I'm failing on this, too. I'm installing to Windows 7 HE. However, what it complains about is that I don't have Git installed. I do have SourceTree, however, and just cloned the IRkernel site to mine.  Is there an alternative to `devtools::install_github('IRkernel/IRkernel')` which I can use to install from my local?  I know how to install from downloaded **R** packages, but don't know if the same logic applies here.  Thanks!

**Comment by flying-sheep** [comment] 2018-11-02 13:48
Yeah, you can download the .zip/.tar.gz from github and install it:

![image](https://user-images.githubusercontent.com/291575/47918962-02571900-dea6-11e8-9c86-6fd1c98c0359.png)

**Comment by harishmohan60** [comment] 2018-11-03 06:47
hey I tried installing with the zip file too. Before the package was in the temp file but I moved it by extracting the ZIP file to the packages folder. when I run this code IRkernel::installspec() in R with in console (cmp), I'm getting the same error (image from the previous post). Please help with this problem, 'flying-sheep' plz!! 
(Ps using R version 3.5.1)

**Comment by flying-sheep** [comment] 2018-11-03 13:55
you need to install jupyter so that it is on your %PATH%

**Comment by flying-sheep** [comment] 2019-01-16 11:45
I haven’t heard back for a while. I’m going to close this. If you still need help, please tell me and I’ll reopen

**Closed by flying-sheep** 2019-01-16 11:45 UTC
Labels: tech support

**Comment by josegarciav** [comment] 2020-05-28 05:11
Hello! 

I am still getting the following error:
Error: Failed to install 'IRkernel' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’

Could you please direct me to how to fix it?

**Comment by flying-sheep** [comment] 2020-05-29 10:03
https://stackoverflow.com/questions/45922418/error-in-install-packages-cannot-remove-prior-installation-of-package-dbi
