### ISSUE TITLE
Jupyter not displaying streaming data

### ISSUE THREAD

**Issue by stramzik** [IRkernel/IRkernel#625] opened 2019-04-25 19:24 UTC
Hi ALl,

I am streaming Twitter data
But when I run the python scripy in other editor it displays normally but when I run the same code in Notebook Nothing happens.
I cell just keep running I guess and no output is displayed and It never completes.
I have to manually interrupt the kernal and even after interrupting it doesnt display the o/p.

Please help.

**Comment by flying-sheep** [comment] 2019-04-26 06:25
Duplicate of #3

**Closed by flying-sheep** 2019-04-26 06:25 UTC

**Comment by ZainRizvi** [comment] 2019-11-01 18:29
@flying-sheep Is it possible to use this solution if the loop is inside some other library?  In my case, the loop is hidden inside a function from a library I use.  Since I don't control that library I can't inject flush commands into it

Sample code I'm trying to execute:
https://github.com/dmlc/xgboost/blob/master/R-package/demo/gpu_accelerated.R

Lines 38 & 44 contain the looping

**Comment by flying-sheep** [comment] 2019-11-04 13:36
That’s currently impossible because the `evaluate` package uses an internal connection. You’d need to implement an uption there so it autoflushes after encountering either of `\n` and `\r`.

Please raise this with https://github.com/r-lib/evaluate.

**Comment by slavistan** [comment] 2020-07-30 14:14
> That’s currently impossible because the `evaluate` package uses an internal connection.

May I kindly ask whether there have been any updates to this problem?

**Comment by flying-sheep** [comment] 2020-07-30 16:32
No, but also nobody filed an issue in the evaluate repo I linked above.

**Comment by fkohrt** [comment] 2022-12-21 21:36
Unfortunately, according to r-lib/evaluate#115,

> __evaluate__ doesn't support displaying streaming data.

So it seems that for continuous communication functions can do one of the following:

- `flush.console()` after `print()`ing
- use `message()`
- write to files
- use other frameworks (e.g. {nanonext})

**Comment by fkohrt** [comment] 2023-01-27 03:27
For scenarios where foreign packages eventually rely on the `base::print()` function to continuously relay information, one could use the functions provided below to effectively flush after every `print()`. __Note, however, that these functions use internal languages features and may break other things. They should not be used in packages.__

Call `use_flush()` right before and `reset_flush()` right after the foreign package does its job. If something does not work one can also try calling `use_flush(globalenv = FALSE)` instead.

```r
#' Setup flush after printing
#'
#' @description Call [flush.console()] after every call to [print()].
#' @param globalenv Bind the original [base::print()] to the
#'   global environment. Otherwise it will be bound to the
#'   base namespace.
use_flush <- function(globalenv = TRUE) {
  ns_env <- rlang::ns_env("base")
  if (globalenv) {
    if (!exists(x = ".base_print",
      where = globalenv(),
      mode = "function")) {
      assign(x = ".base_print", value = base::print, envir = globalenv())
    }
    flush_print <- function (x, ...) {
      val <- .base_print(x, ...)
      flush.console()
      invisible(val)
    }
  } else {
    if (!exists(x = "base_print",
      where = "package:base",
      mode = "function")) {
      rlang::env_unlock(ns_env)
      assign(x = "base_print", value = base::print, envir = ns_env)
      rlang::env_lock(ns_env)
    }
    flush_print <- function (x, ...) {
      val <- base_print(x, ...)
      flush.console()
      invisible(val)
    }
  }
  environment(flush_print) <- ns_env
  unlockBinding(sym = "print", env = ns_env)
  assign(x = "print", value = flush_print, envir = ns_env)
  lockBinding(sym = "print", env = ns_env)
  rm(ns_env)
  rm(flush_print)
}

#' Reset print function
#'
#' @description Reverts the changes introduced by
#'   `use_flush(globalenv = TRUE)`. Note that not it is
#'   impossible to unbind objects from the {base}
#'   namespace and thus there will be leftovers if
#'   `use_flush(globalenv = FALSE)` has been used.
#'   These leftovers should not, however, have any
#'   impact on the restored functionality.
reset_flush <- function() {
  ns_env <- rlang::ns_env("base")
  unlockBinding(sym = "print", env = ns_env)
  if (exists(x = "base_print",
    where = "package:base",
    mode = "function")) {
    assign(x = "print", value = base::base_print, envir = ns_env)
  } else if (exists(x = ".base_print",
    where = globalenv(),
    mode = "function")) {
    assign(x = "print", value = .base_print, envir = ns_env)
    rlang::env_unbind(env = globalenv(), nms = "base_print")
  }
  lockBinding(sym = "print", env = ns_env)
  rm(ns_env)
}
```

For the adventurous it is also possible to call `use_flush()` in the `.Rprofile` and thus benefit from instant feedback in every Jupyter notebook.

Explanation: At its core, `use_flush()` does something like the following:

```r
# Store original print function
base_print <- base::print
# Define new print function that calls the original one and then flushes
flush_print <- function (x, ...) {
  val <- base_print(x, ...)
  flush.console()
  invisible(val)
}
# Retrieve the namespace environment of {base}
ns_env <- rlang::ns_env(x = "base")
# Allow the new print function to access internals from {base}
environment(flush_print) <- ns_env
# Store the new print function in the namespace environment
unlockBinding("print", ns_env)
assign(x = "print", value = flush_print, envir = ns_env)
lockBinding("print", ns_env)
```

The `globalenv` switch controls whether the original print function is stored in the global environment or in the namespace environment of {base}.

In case anybody asks: [CC0](https://creativecommons.org/publicdomain/zero/1.0/)
