### ISSUE TITLE
text of plots are shown as blank square boxes

### ISSUE THREAD

**Issue by frlender** [IRkernel/IRkernel#680] opened 2021-04-07 05:02 UTC
- [x] I followed the [official installation instructions](https://irkernel.github.io/installation/)
  
- [x] I reproduced the error with the newest versions of `IRkernel`, `IRdisplay`, and `repr`
  
- [x] I included a [minimal reproducible example](https://stackoverflow.com/a/5963610/247482)
- [x] This the right repository: I think the issue is with IRkernel, not
      [IRkernel/repr](https://github.com/IRkernel/repr/issues/new) or a third party repository
  
environment:
centos 6.5, anaconda python 3.8.5, R 4.0.3, IRkernel 1.1.1

Code

```r
library(ggplot2)
data(iris)
p <- ggplot(iris, aes(Sepal.Length, Petal.Length, colour=Species)) + geom_point()
p
```

![image](https://user-images.githubusercontent.com/4622635/113812705-1ef78980-97a1-11eb-9385-2be7ddbd7470.png)

The texts of the plots from ggplot and plot function are all shown as blank boxes. But plotly works fine. I am now using plotly for figures but would like to know if I can fix this problem. Thanks!

**Comment by flying-sheep** [comment] 2021-04-07 07:52
Works for me. Can you please write a Dockerfile or so reproducing the error?

I don’t have the time to investigate what kind of weird system configuration might lead to that.

**Comment by frlender** [comment] 2021-04-08 04:08
Thanks for your quick response. The infrastructure I am working on does not have Docker available. I found if I save the plot in PDF format, the text will appear. I can then use IRdisplay to show the figure in notebook. I will use this workaround for now.

**Comment by flying-sheep** [comment] 2021-04-08 11:11
Yeah, R plotting is a wildly complex system that relies on dozens of compile time and runtime variables.

Slim chance that I can support all of that *or* infer what’s wrong without having debugging access to a bugged system.

I’ll close this until someone can help me reproduce it.

**Closed by flying-sheep** 2021-04-08 11:11 UTC
Labels: needs info
