### ISSUE TITLE
Paths autocompletion adds quotes those R cannot interpret

### ISSUE THREAD

**Issue by Sodbo** [IRkernel/IRkernel#661] opened 2020-07-15 11:54 UTC
Dear JN developers,

I am using JN with R Kernel. I used to use an autocompletion of paths to files a lot and it had worked fine. However, half a year ago, autocompletion changed its behavior. It adds unnecessary quotes to the path that blocks me to use TAB again to go deeper into the folders. Screenshots are attached. Configuration of my server, JN version, and IRkernel version are attached.

![quotes_R_JN](https://user-images.githubusercontent.com/7702600/87540208-7745a300-c6c9-11ea-89d8-dd47eb77358d.png)

R version
platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          6.3                         
year           2020                        
month          02                          
day            29                          
svn rev        77875                       
language       R                           
version.string R version 3.6.3 (2020-02-29)
nickname       Holding the Windsock 

IRkernel version: 1.1

Jupyter Notebook version:
jupyter core     : 4.6.1
jupyter-notebook : 6.0.3
qtconsole        : 4.6.0
ipython          : 7.12.0
ipykernel        : 5.1.4
jupyter client   : 5.3.4
jupyter lab      : 1.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3

**Comment by karldw** [comment] 2020-07-16 03:14
Not an IRkernel developer, but is this a duplicate of https://github.com/IRkernel/IRkernel/issues/626?

**Comment by flying-sheep** [comment] 2020-07-16 14:12
Yes, and I should long have submitted a new version of the package.

I just tried, but the package submission form seems to be broken at the moment…

**Closed by flying-sheep** 2020-07-16 14:12 UTC
