### ISSUE TITLE
Kernel crash: Segfault on plotting

### ISSUE THREAD

**Issue by nnmm** [IRkernel/IRkernel#186] opened 2015-09-04 13:46 UTC
Hi,
Both on the demo website (https://try.jupyter.org/) and when running the `jupyter/demo` docker container locally, the kernel crashes with a segfault on plotting. I can execute R commands like `x <- 1:10`, but producing graphics, e. g. `plot(x)` results in a "Kernel Restarting" message and the following output:

```
[I 13:01:51.210 NotebookApp] Kernel started: ed70392a-14ad-4ee0-a568-ebbb97ec9ef9
> IRkernel::main()

 *** caught segfault ***
address 0x35da0, cause 'memory not mapped'

Traceback:
 1: png(tf, width, height, "in", pointsize, bg, res, antialias = antialias)
 2: dev.cb(tf)
 3: repr_recordedplot_generic(obj, ".png", TRUE, function(tf) png(tf,     width, height, "in", pointsize, bg, res, antialias = antialias))
 4: repr_png.recordedplot(plotobj)
 5: mime2repr[[mime]](plotobj)
 6: doTryCatch(return(expr), name, parentenv, handler)
 7: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 8: tryCatchList(expr, classes, parentenv, handlers)
 9: tryCatch(formats[[mime]] <- mime2repr[[mime]](plotobj), error = handle_error)
10: send_plot(last_recorded_plot)
11: executor$execute(msg)
12: handle_shell()
13: kernel$run()
14: IRkernel::main()
```
I actually managed to get a plot to show up once, but I can't describe what I did differently.
The docker file for the demo is probably [this one](https://github.com/jupyter/docker-demo-images/blob/master/Dockerfile).

**Comment by takluyver** [comment] 2015-10-06 13:38
Sorry no-one responded to this sooner. A similar issue was reported (#192) and turned out to be some problem with try.jupyter.org, and it seems to be fixed now. Closing for now, but let us know if you can still reproduce the problem.

**Closed by takluyver** 2015-10-06 13:38 UTC

**Comment by nnmm** [comment] 2015-10-07 22:18
It did not seem to be an issue with the try.jupyter.org website, as the container, run locally, had the same problem. However, everything works with the newest version of the jupyter/demo container.

**Comment by SpiritusPrana** [comment] 2016-03-11 16:03
This R kernel failure has started occurring intermittently again on try.jupyter.org. 

To recreate the error: Select New/Workbook/R.  It opens the new tab and fails to initiate the kernel.  Within the last hour I had this happen three times on try.jupyter.org using both Chrome and Safari.  I closed the window and re-opened it and now I have a kernel running.  Absolutely nothing done differently between the attempts that failed and the one that worked.

I am also consistently experiencing the same issue on a local implementation of the kernel using Jupyter in Anaconda on a Macbook running El Capitan.  On this install I consistently get the same symptoms as the O.P. above (different memory address, same error report).  The kernel was installed using the conda r-essentials package.

**Comment by A1M1** [comment] 2016-05-05 18:10
I am facing the same issue on a local installation. It is consistent and happens whenever I try to plot something. Even a `plot(1:5)` gives that error. I can see a segfault in the logs and the kernel crashing and restarting. I am running it on IRKernel on a Jupyter installation on a Redhat machine. The kernel was also installed using conda like @SpiritusPrana 

Is there an open issue for Jupyter that we could add our data to?

**Comment by luborliu** [comment] 2016-06-08 22:33
@SpiritusPrana so how did you solve this issue in the end? I am having the same issue with plotting function. I have a discussion in https://github.com/IRkernel/IRkernel/issues/313
