### ISSUE TITLE
Reinstall IRkernel doesn't work

### ISSUE THREAD

**Issue by stevenveenma** [IRkernel/IRkernel#574] opened 2018-06-28 12:50 UTC
I used to have IRkernal working properly in windows 7. But I de-installed the old version of R and installed a new version of R (3.5). I choosed to install all  libraries again. Unfortunately I can't get IR kernel to work again. I get the message below:
```
Warning message:
GitHub repo contains submodules, may not function as expected! 
```
This message has been discussed frequently (#461, #513, #485, #487) and I tried all suggestions but nothing helps. Perhaps the old installation is affecting the new one. Any suggestions?

**Comment by flying-sheep** [comment] 2018-06-28 13:11
that message is completely misleading and irrelevant, please ignore it.

there should be different, relevant output that could help to diagnose the problem.

**Comment by stevenveenma** [comment] 2018-06-28 13:14
This is the complete story (after installing devtools and other dependencies):
`
> devtools::install_github('IRkernel/IRkernel')
Downloading GitHub repo IRkernel/IRkernel@master
from URL https://api.github.com/repos/IRkernel/IRkernel/zipball/master
Installing IRkernel
"C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --no-site-file --no-environ  \
  --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/nl26441/AppData/Local/Temp/RtmpWu7ZQN/devtools255c4a015ae3/IRkernel-IRkernel-97c492b"  \
  --library="C:/Users/nl26441/Documents/R/win-library/3.5"  \
  --install-tests 

* installing *source* package 'IRkernel' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'IRkernel'
    finding HTML links ... done
    Comm-class                              html  
    CommManager-class                       html  
    IRkernel                                html  
    comm_manager                            html  
    installspec                             html  
    log_-times                              html  
    main                                    html  
** building package indices
** testing if installed package can be loaded
* DONE (IRkernel)
In R CMD INSTALL
Warning message:
GitHub repo contains submodules, may not function as expected! 
`

**Comment by stevenveenma** [comment] 2018-06-28 13:17
And this when I continue:
`IRkernel::installspec()
Error in IRkernel::installspec() : 
  jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 3.`

**Comment by flying-sheep** [comment] 2018-06-28 13:19
- `* DONE (IRkernel)` means it was installed correctly.
- `jupyter-client has to be installed but “jupyter kernelspec --version” exited with code 3.` means that you have to install the python package `jupyter-client` and that you have to be able to run `jupyter kernelspec --version` from the terminal.

**Comment by flying-sheep** [comment] 2018-06-28 13:20
closing because this is not a bug, but i’ll continue to help you!

**Closed by flying-sheep** 2018-06-28 13:20 UTC
Labels: tech support

**Comment by stevenveenma** [comment] 2018-06-28 13:21
https://stackoverflow.com/questions/44056164/jupyter-client-has-to-be-installed-but-jupyter-kernelspec-version-exited-wit

Found it myself, sorry for the disturbance.

**Comment by flying-sheep** [comment] 2018-06-28 14:52
No problem, please come back if you have another issue :smile:
