### ISSUE TITLE
capturing STDOUT/STDERR

### ISSUE THREAD

**Issue by jeroenooms** [IRkernel/IRkernel#17] opened 2014-04-05 06:47 UTC
It seems as if `STDOUT` and `STDERR` are piped to the server console, see e.g. the R startup message, or output from `install.packages`. These streams often contain important information for the user. Is there some way to display these in the client? 

![screenshot](http://i.imgur.com/Rhaczb2.png)

**Comment by flying-sheep** [comment] 2015-12-19 18:04
dupe of #3?

**Closed** 2016-01-25 12:50 UTC

**Comment by ma1112** [comment] 2025-06-03 13:12
Nope, this issue is not a dupe of #3. This is still an issue with the latest IRKernel version.

I could argue that `evaluate()` should return all messages printed by the evaluated code, including the ones printed in the lower C layer, so it might be OK to keep this issue closed.
But I did not like the verdict here that this is a dupe of #3.
