### ISSUE TITLE
unable to open file '/dev/null' when plotting graphs

### ISSUE THREAD

**Issue by randy3k** [IRkernel/IRkernel#341] opened 2016-05-19 16:15 UTC
I am not sure it is due to which commits, but it happens just after updating R to 3.3 and IRKernel and IRDisplay to their master branches.

```
Error in dev.off(dev): QuartzBitmap_Output - unable to open file '/dev/null'
Traceback:
```

![screen shot 2016-05-19 at 12 14 19 pm](https://cloud.githubusercontent.com/assets/1690993/15400879/38df0df6-1dbb-11e6-9c3d-58c31f4d5d02.png)

MAC OSX 10.11, Jupiter 4.1, R 3.3, IRKernel (master) and IRDisplay (master)

**Comment by takluyver** [comment] 2016-05-19 16:30
:confused:  Not sure how it can fail to open `/dev/null`, but if this can be an issue on Macs, maybe we should revert it.

**Comment by flying-sheep** [comment] 2016-05-20 09:23
wtf… can you do a `ls -l /dev/null`?

can we check if this is common on macs or just some strange thing on @randy3k’s system?

**Comment by flying-sheep** [comment] 2016-05-20 09:31
generally `/dev/null` is specified by POSIX.

a sometimes seen mistake is to `sudo mv -f thing /dev/null` which replaces it. maybe @randy3k did this.

opening and writing to it really should work.

**Comment by flying-sheep** [comment] 2016-05-20 09:58
so in [QuartzBitmap_Output](http://docs.rexamine.com/R-devel/qdBitmap_8c.html#a7f70b78075d2079e351847cda7bf3d4d), [CGImageDestinationCreateWithURL](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/CGImageDestination/#//apple_ref/c/func/CGImageDestinationCreateWithURL). if it doesn’t turn out to be a problem with @randy3k’s `/dev/null` we can investigate here

**Comment by flying-sheep** [comment] 2016-05-20 11:02
@takluyver said:

> Regarding `/dev/null`, I agree that we should investigate more before changing anything, but the fact that we got a bug report almost as soon as we introduced that code makes me worry that it's going to be problematic. So I think unless we can find a clear reason that that was a weird outlier, we should err on the side of avoiding it, as annoying as that is.

that’s a reasonable line of thought. on the other hand i haven’t found anything about any problems with `/dev/null` on OSX in the internet, all problems people have were due to fucking with the file. let’s first have the issue reporter say something about his system before doing anything. if the file has the right node type and permissions on his system, then there’s probably a problem for us. (i just checked, for a friend on OSX, it’s also `crw-rw-rw-`). let’s continue this discussion in #341, please

so this PR can be merged if the three goals in my previous comment are fullfilled, and if a) either the `/dev/null` thing can be confirmed to be a systematic OSX problem, or b) the reverting commit is removed.

**Comment by randy3k** [comment] 2016-05-20 13:26
The permission doesn't seem to be a problem. (I also tried to rebuild it, see the timestamp)

```
(rmbpro)-~$ ls -l /dev/null
crw-rw-rw-  1 root  wheel    3,   2 May 20 09:22 /dev/null
(rmbpro)-~$ R --slave -e 'png("/dev/null"); plot(1); dev.off()'
Error in dev.off() : 
  QuartzBitmap_Output - unable to open file '/dev/null'
Execution halted
```

**Comment by flying-sheep** [comment] 2016-05-20 13:51
OK… damn.

does `R --slave -e 'png("/dev/null", type = "Xlib"); plot(1); dev.off()'` work for you?

**Comment by randy3k** [comment] 2016-05-20 13:57
I don't have ghostscript installed  to try `bitmap`, but postscript works
```
(rmbpro)-~$ R --slave -e 'postscript("/dev/null"); plot(1); dev.off()'
null device 
          1 
```

**Comment by flying-sheep** [comment] 2016-05-20 14:00
`bitmap` only works with ghostscript? i thought only `dev2bitmap` needs that?

**Comment by randy3k** [comment] 2016-05-20 14:01
It is what is shown.

```
(rmbpro)-~$ R --slave -e 'bitmap("/dev/null"); plot(1); dev.off()'
Error in bitmap("/dev/null") : GhostScript was not found
Execution halted
```

**Comment by flying-sheep** [comment] 2016-05-20 14:02
ah, OK! thank you.

the whole idea for the commit that causes problems on OSX is to get away from `pdf`, since that one prints stupid warning messages, even if it’s just used internally without producing any file.

**Comment by randy3k** [comment] 2016-05-20 14:05
perhaps only applying the change to windows/linux platforms?

**Comment by flying-sheep** [comment] 2016-05-20 14:07
good idea. can you execute this please?

```r
R --slave -e 'pdf("/dev/null"); plot(1, main="–"); dev.off()'
```

**Comment by randy3k** [comment] 2016-05-20 14:07
It does
```
(rmbpro)-~$ R --slave -e 'pdf("/dev/null"); plot(1, main="–"); dev.off()'
Warning messages:
1: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <e2>
2: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <80>
3: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <93>
4: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <e2>
5: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <80>
6: In title(...) :
  conversion failure on '–' in 'mbcsToSbcs': dot substituted for <93>
null device 
          1 
```

**Comment by flying-sheep** [comment] 2016-05-20 14:11
well, postscript also does. fak.

last ditch: pictex?

**Comment by randy3k** [comment] 2016-05-20 14:14
```
(rmbpro)-~$ R --slave -e 'pictex("/dev/null"); plot(1, main="–"); dev.off()'
null device 
          1 
```

I don't have much experiences on how the plots are rendered, try is the one thing I could offer.

**Comment by flying-sheep** [comment] 2016-05-20 14:16
great, it seems to work! let’s use it then.

**Closed** 2016-05-20 14:18 UTC

**Comment by flying-sheep** [comment] 2016-05-20 14:43
someone advised against it as it is so old that it might not record stuff correctly but it seems to do so just fine.

i hope this is the end of this issue

**Comment by janschulz** [comment] 2016-05-21 16:55
lets try it, but my vote would goes to stable code (=use one of the default devices) over code without warnings (which only happen in some "obscure" cases). I can also live with png which would write to a tempfile. Not sure what we did up to now (where did the pdf device write to?)

**Comment by randy3k** [comment] 2016-05-21 17:44
I believe that evaluate [uses](https://github.com/hadley/evaluate/blob/v0.9/R/eval.r#L55) `pdf(file = NULL)`.

**Comment by flying-sheep** [comment] 2016-05-22 22:05
> lets try it, but my vote would goes to stable code (=use one of the default devices) over code without warnings (which only happen in some "obscure" cases)

actually the case is very common: “everywhere but on windows when using the default device (PDF)”

so this is necessary

**Comment by janschulz** [comment] 2016-05-22 23:06
If this would be common (and/or it would bother someone), someone would have fixed it upstream... But maybe RStudio and there default device is doing exactly that?

**Comment by flying-sheep** [comment] 2016-05-23 07:30
well, if you’d actually *use* the PDF device the warnings make sense, since you indeed won’t see some characters then. but we only need a device capable of recording draw calls that we will play back to the actual devices we configured.

**Comment by janschulz** [comment] 2016-05-25 21:08
For more fun with graphic devices in R: https://github.com/hrbrmstr/r_device_tests
