### ISSUE TITLE
Download as pdf via LaTex not working

### ISSUE THREAD

**Issue by clarknie** [IRkernel/IRkernel#143] opened 2015-05-29 16:34 UTC
I have Mac OSX. When I have a iPython notebook with R kernel running, I want to download a pdf report of the notebook. However, it gives me error message of:

500 : Internal Server Error
nbconvert failed: PDF creating failed

However, the function of download as pdf would work for a iPython notebook with my Python 2 Kernel. How shall I make it work? The reason why I want to download it as pdf is because I inserted a local image into the notebook with markdown. Downloading the notebook as html, r, rst, md would not include this local image.

**Comment by takluyver** [comment] 2015-05-29 21:28
HTML should include it, and if you convert to markdown or restructuredtext it should save it to a separate file and link it in correctly.

Conversion to PDF actually makes Latex and then runs pdflatex on it. So it's probably Latex that's failing. Can you try `ipython nbconvert --to pdf mynotebook.ipynb` at the command line to see what the issue is?

**Comment by clarknie** [comment] 2015-05-31 03:57
Thank you, takluyver. The output from the command you suggested is complaining about pdflatex. I am not sure how I could correct it. But I do have a workaround for this problem. The workaround is simply directly print the notebook from browser and save it as pdf file. The output of the command is very lengthy:

ipython nbconvert --to pdf models.ipynb 
[NbConvertApp] Converting notebook models.ipynb to pdf
[NbConvertApp] Writing 95337 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2011/06/27>
Babel <3.9f> and hyphenation patterns for 78 languages loaded.
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2013/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/xkeyval/xkeyval.tex))
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/local/texlive/2013/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2013/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/booktabs/booktabs.sty)
No file notebook.aux.
(/usr/local/texlive/2013/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

Package geometry Warning: The marginal notes overrun the paper.
     Add 3.73001pt and more to the right margin.

*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=10.0pt
* \footskip=30.0pt
* \marginparwidth=65.0pt
* \marginparsep=11.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

[1{/usr/local/texlive/2013/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
[2]

! LaTeX Error: Environment description* undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.423     \begin{description*}
                              
? 
! Emergency stop.
 ...                                              
                                                  
l.423     \begin{description*}
                              
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

[NbConvertApp] Running bibtex 1 time: [u'bibtex', u'notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] CRITICAL | pdflatex failed: [u'pdflatex', u'notebook.tex']
This is pdfTeX, Version 3.1415926-2.5-1.40.14 (TeX Live 2013)
 restricted \write18 enabled.
entering extended mode
(./notebook.tex
LaTeX2e <2011/06/27>
Babel <3.9f> and hyphenation patterns for 78 languages loaded.
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/article.cls
Document Class: article 2007/10/19 v1.4h Standard LaTeX document class
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/size10.clo))
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/graphics.cfg)
(/usr/local/texlive/2013/texmf-dist/tex/latex/pdftex-def/pdftex.def
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/infwarerr.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ltxcmds.sty))))
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/adjustbox.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/xkeyval/xkeyval.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/xkeyval/xkeyval.tex))
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/adjcalc.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/trimclip.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/collectbox/collectbox.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/adjustbox/tc-pdftex.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/ifoddpage/ifoddpage.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/varwidth/varwidth.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/graphics/color.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/color.cfg))
(/usr/local/texlive/2013/texmf-dist/tex/latex/tools/enumerate.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifpdf.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifvtex.sty)
(/usr/local/texlive/2013/texmf-dist/tex/generic/ifxetex/ifxetex.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/amssymb.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/amsfonts.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/eurosym/eurosym.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/ucs.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/data/uni-global.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/base/inputenc.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/utf8x.def))
(/usr/local/texlive/2013/texmf-dist/tex/latex/fancyvrb/fancyvrb.sty
Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
<2008/02/07> (tvz))
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/grffile.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/kvoptions.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/kvsetkeys.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/etexcmds.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/ifluatex.sty))))
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/pdftexcmds.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-hyperref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/hobsub-generic.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/auxhook.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/pd1enc.def)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/hyperref.cfg)
(/usr/local/texlive/2013/texmf-dist/tex/latex/url/url.sty))

Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/local/texlive/2013/texmf-dist/tex/latex/tools/longtable.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/booktabs/booktabs.sty)
(./notebook.aux)
(/usr/local/texlive/2013/texmf-dist/tex/context/base/supp-pdf.mkii
[Loading MPS to PDF converter (version 2006.09.02).]
) (/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/epstopdf-base.sty
(/usr/local/texlive/2013/texmf-dist/tex/latex/oberdiek/grfext.sty)
(/usr/local/texlive/2013/texmf-dist/tex/latex/latexconfig/epstopdf-sys.cfg))
*geometry* driver: auto-detecting
*geometry* detected driver: pdftex

Package geometry Warning: The marginal notes overrun the paper.
     Add 3.73001pt and more to the right margin.

*geometry* verbose mode - [ preamble ] result:
* driver: pdftex
* paper: <default>
* layout: <same size as paper>
* layoutoffset:(h,v)=(0.0pt,0.0pt)
* modes: 
* h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
* v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
* \paperwidth=614.295pt
* \paperheight=794.96999pt
* \textwidth=469.75502pt
* \textheight=650.43001pt
* \oddsidemargin=0.0pt
* \evensidemargin=0.0pt
* \topmargin=-37.0pt
* \headheight=12.0pt
* \headsep=25.0pt
* \topskip=10.0pt
* \footskip=30.0pt
* \marginparwidth=65.0pt
* \marginparsep=11.0pt
* \columnsep=10.0pt
* \skip\footins=9.0pt plus 4.0pt minus 2.0pt
* \hoffset=0.0pt
* \voffset=0.0pt
* \mag=1000
* \@twocolumnfalse
* \@twosidefalse
* \@mparswitchfalse
* \@reversemarginfalse
* (1in=72.27pt=25.4mm, 1cm=28.453pt)

(/usr/local/texlive/2013/texmf-dist/tex/latex/ucs/ucsencs.def)
(/usr/local/texlive/2013/texmf-dist/tex/latex/hyperref/nameref.sty
(/usr/local/texlive/2013/texmf-dist/tex/generic/oberdiek/gettitlestring.sty))
(./notebook.out) (./notebook.out)
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/umsa.fd)
(/usr/local/texlive/2013/texmf-dist/tex/latex/amsfonts/umsb.fd)

LaTeX Warning: No \author given.

[1{/usr/local/texlive/2013/texmf-var/fonts/map/pdftex/updmap/pdftex.map}]
[2]

! LaTeX Error: Environment description* undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.423     \begin{description*}
                              
? 
! Emergency stop.
 ...                                              
                                                  
l.423     \begin{description*}
                              
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on notebook.log.

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ipython", line 5, in <module>
    start_ipython()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/config/application.py", line 574, in launch_instance
    app.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 278, in start
    self.convert_notebooks()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 401, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 372, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/nbconvertapp.py", line 324, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/exporters/exporter.py", line 154, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/IPython/nbconvert/exporters/pdf.py", line 137, in from_notebook_node
    raise RuntimeError("PDF creating failed")
RuntimeError: PDF creating failed

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

**Comment by takluyver** [comment] 2015-05-31 04:06
OK, thanks. Can you file an issue about this on https://github.com/jupyter/nbconvert, and reference this issue? It's not really a problem in the R kernel, though it's probably some output from the R kernel that's triggering it, so I'm going to close this issue.

**Closed by takluyver** 2015-05-31 04:06 UTC

**Comment by clarknie** [comment] 2015-05-31 04:25
[Here](https://github.com/jupyter/nbconvert/issues/27) it is.

**Comment by emadel80** [comment] 2018-07-30 19:52
Hi, everyone!  I am starting to learn python and jupyter notebooks.  I am also having trouble with the conversion from notebook to pdf.  The pdf file is created successfully but I receive a bibtex warning.  I wonder if this is why the python code doesn't appear inside a gray rectangle like in my notebook.  Here's the link to the pdf: [Polynomials Summary.pdf](https://github.com/IRkernel/IRkernel/files/2242661/Polynomials.Summary.pdf).  Also the sections appears as 1. Heading for # Heading and 1.1 Subheading for ## Subheading.  FIrst time I am using it, not sure if this is how the pdf file should be created. 

The warning is found before the last line of the log.  This is the log in my console:
```
Serving notebooks from local directory: /Users/my-user-name/Development/venv/data-science/notebooks/Module01
[I 15:32:13.311 NotebookApp] The Jupyter Notebook is running at:
[I 15:32:13.311 NotebookApp] http://localhost:8888/?token=a943bdf958a20a94135a98174d86bd04b5f47532b3569e56
[I 15:32:13.311 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:32:13.315 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=a943bdf958a20a94135a98174d86bd04b5f47532b3569e56
[I 15:32:15.975 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 15:32:25.731 NotebookApp] Kernel started: 9c0f7f26-7a51-442b-b8c5-dc937fd93ae2
[I 15:32:28.760 NotebookApp] Adapting to protocol v5.1 for kernel 9c0f7f26-7a51-442b-b8c5-dc937fd93ae2
[I 15:33:00.887 NotebookApp] Writing 25960 bytes to /Users/emanuel/Development/venv/data-science/notebooks/Module01/notebook.tex
[I 15:33:00.892 NotebookApp] Building PDF
[I 15:33:00.893 NotebookApp] Running xelatex 3 times: ['xelatex', '/Users/emanuel/Development/venv/data-science/notebooks/Module01/notebook.tex']
[I 15:33:03.007 NotebookApp] Running bibtex 1 time: ['bibtex', '/Users/emanuel/Development/venv/data-science/notebooks/Module01/notebook']
[W 15:33:03.044 NotebookApp] bibtex had problems, most likely because there were no citations
[I 15:33:03.044 NotebookApp] PDF successfully created
```
Please, help me.

**Comment by flying-sheep** [comment] 2018-07-30 21:12
hmm, “bibtex had problems, most likely because there were no citations” is relatively clear, the fix isn’t.

i assume either the template or the otherwise default behavior for exports to PDF makes it run bibtex, which complains when there’s no citations in the document (because usually one wouldn’t manually run bibtex on a document without citations). i don’t know where to fix this, but i assume it’s not here, but some jupyter/* repository.

**Comment by emadel80** [comment] 2018-07-30 21:51
Thank you, for your reply flying-sheep.  It is good to know what bibtex is about.  You are right, I'm not trying to create the pdf manually.  The jupyter notebook does by using commands like nbconvert, xelatex, bibtex, etc.  I'll look for jupyter forums and ask there then.
