### ISSUE TITLE
Support `input_request` / interactive debugger support for IRkernel

### ISSUE THREAD

**Issue by ngr-t** [IRkernel/IRkernel#442] opened 2017-01-29 04:02 UTC
Dear maintainers,

Currently IRkernel does not deal with `input_request` type message to allow user to input text.  How about supporting this?
I think it can be achieved by implementing a customized version of `readline()` which follows Jupyter protocol, and mask `base::readline()` by set it in global name space, make it a tracer of `base::readline()` function or some other way. Of course it's also necessary to modify the kernel to send / receive input_request / reply.

A topic related to this, I want an interactive debugger for IRkernel. Maybe I can achieve it by the same line as I said about `readline()`.

Any suggestions?

Thanks

**Comment by takluyver** [comment] 2017-01-29 09:40
Yep, I think this is a good idea. See also #199.

**Comment by flying-sheep** [comment] 2017-01-29 10:24
yes, this is a duplicate of #199. let’s keep the number of open issues low.

**Closed by flying-sheep** 2017-01-29 10:24 UTC
Labels: interactive
